# -*- coding: utf-8 -*-
"""statistics3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GWCJlsltGdFsS4yWanbQ2_Wii6HFCNs8
"""

import numpy as np
from scipy import stats

before = np.array([78, 82, 85, 90, 76, 80, 78, 74,
                   88, 92, 89, 85, 80, 75, 82, 81,
                   79, 87, 91, 86])

after = np.array([85, 84, 88, 92, 79, 82, 81, 78,
                  90, 94, 91, 87, 83, 80, 85, 84,
                  82, 90, 95, 89])

before_mean = np.mean(before)
after_mean = np.mean(after)
before_std = np.std(before, ddof=1)
after_std = np.std(after, ddof=1)
diff = after - before
diff_mean = np.mean(diff)
diff_std = np.std(diff, ddof=1)

z_score = diff_mean / (diff_std / np.sqrt(len(diff)))

p_value = 2 * (1 - stats.norm.cdf(abs(z_score)))

print("Before mean:", before_mean)
print("After mean:", after_mean)
print("Difference mean:", diff_mean)
print("Z-score:", z_score)
print("p-value:", p_value)
alpha = 0.05
if p_value < alpha:
    print("Reject null hypothesis: The means are significantly different.")
else:
    print("Fail to reject null hypothesis: ")

