# -*- coding: utf-8 -*-
"""statistic5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1wKMq0jTiH3-IN6BVqrluVCwbvcexkn
"""

import pandas as pd
from scipy.stats import chi2_contingency
import seaborn as sns

titanic = sns.load_dataset('titanic')

contingency_table = pd.crosstab(titanic['survived'], titanic['sex'])

chi2, p, dof, expected = chi2_contingency(contingency_table)

print("contingency_table", contingency_table)
print("Chi-square statistic:", chi2)
print("p-value:", p)
print("Degrees of freedom:", dof)
print('expected frequencie',expected)

if p < 0.05:
    print("Reject the null hypothesis - variables are n")
else:
    print("Fail to reject the null hypothesis - variables are independent")

import scipy.stats as stats
import pandas as pd
import numpy as np

performance1=[89,89,88.78,79]
performance2=[93,92,94,89,88]
performance3=[89,88,89,93,90]
performance4=[81,78,81,92,82]

f_stat,p_value=stats.f_oneway(performance1,performance2,performance3,performance4)
print("F-Statistics:",f_stat)
print("P-Value:",p_value)

alpha=0.05
if p_value<alpha:
    print("Reject the null hypothesis. There is a significant difference in performance.")
else:
    print("Fail to reject the null hypothesis. There is no significant difference in performance.")