# -*- coding: utf-8 -*-
"""word frequency analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14cOwUf8hfHA3kaDQzGpqiFJwMegGkIF9
"""

import re
from collections import Counter

def top_frequent_words(text, N):
    # Clean the text and split into words
    words = re.findall(r'\b\w+\b', text.lower())

    # Count word frequencies
    word_count = Counter(words)

    # Sort words by frequency (desc), then alphabetically
    sorted_words = sorted(word_count.items(), key=lambda x: (-x[1], x[0]))

    # Return the top N words
    return sorted_words[:N]

import re
from collections import Counter

def top_frequent_words(text, N):
    # Clean the text and split into words
    words = re.findall(r'\b\w+\b', text.lower())

    # Count word frequencies
    word_count = Counter(words)

    # Sort words by frequency (desc), then alphabetically
    sorted_words = sorted(word_count.items(), key=lambda x: (-x[1], x[0]))

    # Return the top N words
    return sorted_words[:N]
text = """
Data science is amazing. Data analysis is powerful.
Data and science together are transformative.
"""
N = 3
print(top_frequent_words(text, N))